"""empty message

Revision ID: 352637a04cef
Revises: 686298454738
Create Date: 2023-03-06 15:23:58.417655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '352637a04cef'
down_revision = '686298454738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('student_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('student_name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
