"""empty message

Revision ID: 686298454738
Revises: 
Create Date: 2023-03-06 01:16:53.195990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686298454738'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
