"""empty message

Revision ID: dbed0fd289d7
Revises: 352637a04cef
Create Date: 2023-03-08 23:13:22.471020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbed0fd289d7'
down_revision = '352637a04cef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unverifiedstudents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('grade',
               existing_type=sa.FLOAT(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('grade',
               existing_type=sa.String(),
               type_=sa.FLOAT(),
               existing_nullable=True)

    op.drop_table('unverifiedstudents')
    # ### end Alembic commands ###
